Repository wdhongtw/vscode-gpg-indicator, pull requests merged in 2025-02, with the labels that each got.

#87 Adjust project structure and simplify user messages.
  l10n/bundle.l10n.zh-cn.json
  package.nls.json
  package.nls.zh-cn.json
  src/adapter/assuan.ts
  src/adapter/git.spec.ts
  src/adapter/git.ts
  src/adapter/gpg.spec.ts
  src/adapter/gpg.ts
  src/common/locker.spec.ts
  src/common/locker.ts
  src/common/process.ts
  src/common/tempfile.ts
  src/core.ts
  src/extension.test.ts
  src/extension.ts
  src/message.ts
Labels: documentation, enhancement

#89 Support signing keys starting with 0x
  src/adapter/git.ts
Labels: bug

#91 Add Japanese localization files
  l10n/bundle.l10n.ja.json
  package.nls.ja.json
Labels: enhancement
